# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caritas_pdra_statistics_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from qgis import gui, core
from .resources_rc import *


class Ui_CaritasPDRAStatisticsDialog(object):
    def setupUi(self, CaritasPDRAStatisticsDialog):
        CaritasPDRAStatisticsDialog.setObjectName("CaritasPDRAStatisticsDialog")
        CaritasPDRAStatisticsDialog.resize(720, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CaritasPDRAStatisticsDialog.sizePolicy().hasHeightForWidth())
        CaritasPDRAStatisticsDialog.setSizePolicy(sizePolicy)
        CaritasPDRAStatisticsDialog.setMinimumSize(QtCore.QSize(720, 480))
        CaritasPDRAStatisticsDialog.setMaximumSize(QtCore.QSize(720, 480))
        font = QtGui.QFont()
        font.setPointSize(10)
        CaritasPDRAStatisticsDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/caritas_pdra/img/icons/icon-statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CaritasPDRAStatisticsDialog.setWindowIcon(icon)
        CaritasPDRAStatisticsDialog.setModal(False)
        self.label = QtWidgets.QLabel(CaritasPDRAStatisticsDialog)
        self.label.setGeometry(QtCore.QRect(10, 410, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.caritasLogo = QtWidgets.QLabel(CaritasPDRAStatisticsDialog)
        self.caritasLogo.setGeometry(QtCore.QRect(640, 410, 71, 51))
        self.caritasLogo.setText("")
        self.caritasLogo.setPixmap(QtGui.QPixmap(":/plugins/caritas_pdra/img/logos/logo-nassa-caritas.png"))
        self.caritasLogo.setObjectName("caritasLogo")
        self.buttonBox = QtWidgets.QDialogButtonBox(CaritasPDRAStatisticsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(540, 370, 171, 31))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.selectHHLabel = QtWidgets.QLabel(CaritasPDRAStatisticsDialog)
        self.selectHHLabel.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectHHLabel.setFont(font)
        self.selectHHLabel.setWordWrap(True)
        self.selectHHLabel.setObjectName("selectHHLabel")
        self.selectHHComboBox = gui.QgsMapLayerComboBox(CaritasPDRAStatisticsDialog)
        self.selectHHComboBox.setGeometry(QtCore.QRect(210, 10, 501, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectHHComboBox.setFont(font)
        self.selectHHComboBox.setStatusTip("")
        self.selectHHComboBox.setShowCrs(True)
        self.selectHHComboBox.setObjectName("selectHHComboBox")
        self.selectHHComboBox.setFilters(core.QgsMapLayerProxyModel.PointLayer)
        self.selectAdminLabel = QtWidgets.QLabel(CaritasPDRAStatisticsDialog)
        self.selectAdminLabel.setGeometry(QtCore.QRect(10, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectAdminLabel.setFont(font)
        self.selectAdminLabel.setWordWrap(True)
        self.selectAdminLabel.setObjectName("selectAdminLabel")
        self.selectAdminComboBox = gui.QgsMapLayerComboBox(CaritasPDRAStatisticsDialog)
        self.selectAdminComboBox.setGeometry(QtCore.QRect(210, 60, 501, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectAdminComboBox.setFont(font)
        self.selectAdminComboBox.setStatusTip("")
        self.selectAdminComboBox.setShowCrs(True)
        self.selectAdminComboBox.setObjectName("selectAdminComboBox")
        self.selectAdminComboBox.setFilters(core.QgsMapLayerProxyModel.PolygonLayer)
        self.filterByCategoryLabel = QtWidgets.QLabel(CaritasPDRAStatisticsDialog)
        self.filterByCategoryLabel.setGeometry(QtCore.QRect(10, 110, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filterByCategoryLabel.setFont(font)
        self.filterByCategoryLabel.setWordWrap(True)
        self.filterByCategoryLabel.setObjectName("filterByCategoryLabel")
        self.filterByCategoryComboBox = QtWidgets.QComboBox(CaritasPDRAStatisticsDialog)
        self.filterByCategoryComboBox.setGeometry(QtCore.QRect(210, 110, 501, 31))
        self.filterByCategoryComboBox.setObjectName("filterByCategoryComboBox")
        self.summariesList = QtWidgets.QListWidget(CaritasPDRAStatisticsDialog)
        self.summariesList.setGeometry(QtCore.QRect(510, 190, 201, 171))
        self.summariesList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.summariesList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.summariesList.setObjectName("summariesList")
        item = QtWidgets.QListWidgetItem()
        self.summariesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.summariesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.summariesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.summariesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.summariesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.summariesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.summariesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.summariesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.summariesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.summariesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.summariesList.addItem(item)
        self.summariesToCalculateLabel = QtWidgets.QLabel(CaritasPDRAStatisticsDialog)
        self.summariesToCalculateLabel.setGeometry(QtCore.QRect(510, 160, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.summariesToCalculateLabel.setFont(font)
        self.summariesToCalculateLabel.setWordWrap(True)
        self.summariesToCalculateLabel.setObjectName("summariesToCalculateLabel")
        self.fieldsToSummarizeLabel = QtWidgets.QLabel(CaritasPDRAStatisticsDialog)
        self.fieldsToSummarizeLabel.setGeometry(QtCore.QRect(10, 160, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fieldsToSummarizeLabel.setFont(font)
        self.fieldsToSummarizeLabel.setWordWrap(True)
        self.fieldsToSummarizeLabel.setObjectName("fieldsToSummarizeLabel")
        self.fieldsList = QtWidgets.QListWidget(CaritasPDRAStatisticsDialog)
        self.fieldsList.setGeometry(QtCore.QRect(10, 190, 471, 171))
        self.fieldsList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fieldsList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.fieldsList.setObjectName("fieldsList")
        self.note = QtWidgets.QLabel(CaritasPDRAStatisticsDialog)
        self.note.setGeometry(QtCore.QRect(10, 360, 491, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.note.setFont(font)
        self.note.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.note.setScaledContents(False)
        self.note.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.note.setWordWrap(True)
        self.note.setObjectName("note")

        self.retranslateUi(CaritasPDRAStatisticsDialog)
        QtCore.QMetaObject.connectSlotsByName(CaritasPDRAStatisticsDialog)

    def retranslateUi(self, CaritasPDRAStatisticsDialog):
        _translate = QtCore.QCoreApplication.translate
        CaritasPDRAStatisticsDialog.setWindowTitle(_translate("CaritasPDRAStatisticsDialog", "Caritas PDRA Compute Statistics"))
        self.label.setText(_translate("CaritasPDRAStatisticsDialog", "<html><head/><body><p><span style=\" font-size:6pt;\">This plugin was made possible due to the efforts of NASSA/Caritas Philippines.</span></p></body></html>"))
        self.buttonBox.setToolTip(_translate("CaritasPDRAStatisticsDialog", "Perform Statistics Computation"))
        self.selectHHLabel.setToolTip(_translate("CaritasPDRAStatisticsDialog", "Siguraduhing ang coordinate reference system (hal. EPSG: 32651) ng household at admin layers ay pareho"))
        self.selectHHLabel.setText(_translate("CaritasPDRAStatisticsDialog", "Select Household Layer with PDRA Indicators"))
        self.selectHHComboBox.setToolTip(_translate("CaritasPDRAStatisticsDialog", "Piliin ang household layer na naglalaman ng mga PDRA indicators"))
        self.selectHHComboBox.setWhatsThis(_translate("CaritasPDRAStatisticsDialog", "Select the household point layer with PDRA indicators"))
        self.selectAdminLabel.setToolTip(_translate("CaritasPDRAStatisticsDialog", "Siguraduhing ang coordinate reference system (hal. EPSG: 32651) ng household at admin layers ay pareho"))
        self.selectAdminLabel.setText(_translate("CaritasPDRAStatisticsDialog", "Select the Admin boundary layer"))
        self.selectAdminComboBox.setToolTip(_translate("CaritasPDRAStatisticsDialog", "Piliin ang layer na naglalaman ng administrative boundaries (hal. barangay, munisipalidad, lalawigan)"))
        self.selectAdminComboBox.setWhatsThis(_translate("CaritasPDRAStatisticsDialog", "Select the layer with the admin boundaries"))
        self.filterByCategoryLabel.setText(_translate("CaritasPDRAStatisticsDialog", "Filter Indicators by Category"))
        self.filterByCategoryComboBox.setToolTip(_translate("CaritasPDRAStatisticsDialog", "Pumili ng kategorya"))
        self.summariesList.setToolTip(_translate("CaritasPDRAStatisticsDialog", "Piliin ang mga istatistika na kukwentahin"))
        __sortingEnabled = self.summariesList.isSortingEnabled()
        self.summariesList.setSortingEnabled(False)
        item = self.summariesList.item(0)
        item.setText(_translate("CaritasPDRAStatisticsDialog", "count"))
        item = self.summariesList.item(1)
        item.setText(_translate("CaritasPDRAStatisticsDialog", "unique"))
        item = self.summariesList.item(2)
        item.setText(_translate("CaritasPDRAStatisticsDialog", "min"))
        item = self.summariesList.item(3)
        item.setText(_translate("CaritasPDRAStatisticsDialog", "max"))
        item = self.summariesList.item(4)
        item.setText(_translate("CaritasPDRAStatisticsDialog", "range"))
        item = self.summariesList.item(5)
        item.setText(_translate("CaritasPDRAStatisticsDialog", "sum"))
        item = self.summariesList.item(6)
        item.setText(_translate("CaritasPDRAStatisticsDialog", "mean"))
        item = self.summariesList.item(7)
        item.setText(_translate("CaritasPDRAStatisticsDialog", "median"))
        item = self.summariesList.item(8)
        item.setText(_translate("CaritasPDRAStatisticsDialog", "stddev"))
        item = self.summariesList.item(9)
        item.setText(_translate("CaritasPDRAStatisticsDialog", "majority"))
        item = self.summariesList.item(10)
        item.setText(_translate("CaritasPDRAStatisticsDialog", "minority"))
        self.summariesList.setSortingEnabled(__sortingEnabled)
        self.summariesToCalculateLabel.setText(_translate("CaritasPDRAStatisticsDialog", "Summaries to Calculate"))
        self.fieldsToSummarizeLabel.setText(_translate("CaritasPDRAStatisticsDialog", "Select Fields to Summarize"))
        self.fieldsList.setToolTip(_translate("CaritasPDRAStatisticsDialog", "Piliin ang mga indikador na gagamitin sa pagkwenta ng istatistika"))
        self.note.setText(_translate("CaritasPDRAStatisticsDialog", "<html><head/><body><p><span style=\" font-size:6pt;\">* If only one field and summary statistic is selected, the resulting layer will be labeled with the results of the summarization</span></p></body></html>"))
