# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caritas_pdra_risk_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from qgis import gui, core
from .resources_rc import *


class Ui_CaritasPDRARiskDialog(object):
    def setupUi(self, CaritasPDRARiskDialog):
        CaritasPDRARiskDialog.setObjectName("CaritasPDRARiskDialog")
        CaritasPDRARiskDialog.resize(900, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CaritasPDRARiskDialog.sizePolicy().hasHeightForWidth())
        CaritasPDRARiskDialog.setSizePolicy(sizePolicy)
        CaritasPDRARiskDialog.setMinimumSize(QtCore.QSize(900, 600))
        CaritasPDRARiskDialog.setMaximumSize(QtCore.QSize(900, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        CaritasPDRARiskDialog.setFont(font)
        CaritasPDRARiskDialog.setModal(False)
        self.selectHHComboBox = gui.QgsMapLayerComboBox(CaritasPDRARiskDialog)
        self.selectHHComboBox.setGeometry(QtCore.QRect(310, 20, 441, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectHHComboBox.setFont(font)
        self.selectHHComboBox.setObjectName("selectHHComboBox")
        self.selectHHComboBox.setFilters(core.QgsMapLayerProxyModel.PointLayer)
        self.selectHHLabel = QtWidgets.QLabel(CaritasPDRARiskDialog)
        self.selectHHLabel.setGeometry(QtCore.QRect(10, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectHHLabel.setFont(font)
        self.selectHHLabel.setWordWrap(True)
        self.selectHHLabel.setObjectName("selectHHLabel")
        self.resultBasenameLabel = QtWidgets.QLabel(CaritasPDRARiskDialog)
        self.resultBasenameLabel.setGeometry(QtCore.QRect(10, 60, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resultBasenameLabel.setFont(font)
        self.resultBasenameLabel.setWordWrap(True)
        self.resultBasenameLabel.setObjectName("resultBasenameLabel")
        self.resultBasenameLineEdit = QtWidgets.QLineEdit(CaritasPDRARiskDialog)
        self.resultBasenameLineEdit.setGeometry(QtCore.QRect(310, 60, 441, 27))
        self.resultBasenameLineEdit.setObjectName("resultBasenameLineEdit")
        self.selectIndicatorsLabel = QtWidgets.QLabel(CaritasPDRARiskDialog)
        self.selectIndicatorsLabel.setGeometry(QtCore.QRect(10, 100, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.selectIndicatorsLabel.setFont(font)
        self.selectIndicatorsLabel.setObjectName("selectIndicatorsLabel")
        self.hazLabel = QtWidgets.QLabel(CaritasPDRARiskDialog)
        self.hazLabel.setGeometry(QtCore.QRect(10, 120, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hazLabel.setFont(font)
        self.hazLabel.setObjectName("hazLabel")
        self.hazListWidget = QtWidgets.QListWidget(CaritasPDRARiskDialog)
        self.hazListWidget.setGeometry(QtCore.QRect(10, 150, 281, 291))
        self.hazListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.hazListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.hazListWidget.setObjectName("hazListWidget")
        self.vulListWidget = QtWidgets.QListWidget(CaritasPDRARiskDialog)
        self.vulListWidget.setGeometry(QtCore.QRect(310, 150, 281, 291))
        self.vulListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.vulListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.vulListWidget.setObjectName("vulListWidget")
        self.capListWidget = QtWidgets.QListWidget(CaritasPDRARiskDialog)
        self.capListWidget.setGeometry(QtCore.QRect(610, 150, 281, 291))
        self.capListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.capListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.capListWidget.setObjectName("capListWidget")
        self.vulLabel = QtWidgets.QLabel(CaritasPDRARiskDialog)
        self.vulLabel.setGeometry(QtCore.QRect(310, 120, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.vulLabel.setFont(font)
        self.vulLabel.setObjectName("vulLabel")
        self.capLabel = QtWidgets.QLabel(CaritasPDRARiskDialog)
        self.capLabel.setGeometry(QtCore.QRect(610, 120, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.capLabel.setFont(font)
        self.capLabel.setObjectName("capLabel")
        self.hazSelectAllBtn = QtWidgets.QPushButton(CaritasPDRARiskDialog)
        self.hazSelectAllBtn.setGeometry(QtCore.QRect(10, 450, 101, 25))
        self.hazSelectAllBtn.setObjectName("hazSelectAllBtn")
        self.hazUnselectAllBtn = QtWidgets.QPushButton(CaritasPDRARiskDialog)
        self.hazUnselectAllBtn.setGeometry(QtCore.QRect(190, 450, 101, 25))
        self.hazUnselectAllBtn.setObjectName("hazUnselectAllBtn")
        self.vulUnselectAllBtn = QtWidgets.QPushButton(CaritasPDRARiskDialog)
        self.vulUnselectAllBtn.setGeometry(QtCore.QRect(490, 450, 101, 25))
        self.vulUnselectAllBtn.setObjectName("vulUnselectAllBtn")
        self.vulSelectAllBtn = QtWidgets.QPushButton(CaritasPDRARiskDialog)
        self.vulSelectAllBtn.setGeometry(QtCore.QRect(310, 450, 101, 25))
        self.vulSelectAllBtn.setObjectName("vulSelectAllBtn")
        self.capUnselectAllBtn = QtWidgets.QPushButton(CaritasPDRARiskDialog)
        self.capUnselectAllBtn.setGeometry(QtCore.QRect(790, 450, 101, 25))
        self.capUnselectAllBtn.setObjectName("capUnselectAllBtn")
        self.capSelectAllBtn = QtWidgets.QPushButton(CaritasPDRARiskDialog)
        self.capSelectAllBtn.setGeometry(QtCore.QRect(610, 450, 101, 25))
        self.capSelectAllBtn.setObjectName("capSelectAllBtn")
        self.label = QtWidgets.QLabel(CaritasPDRARiskDialog)
        self.label.setGeometry(QtCore.QRect(10, 530, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CaritasPDRARiskDialog)
        self.label_2.setGeometry(QtCore.QRect(820, 530, 71, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/plugins/caritas_pdra/img/logos/logo-nassa-caritas.png"))
        self.label_2.setObjectName("label_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(CaritasPDRARiskDialog)
        self.buttonBox.setGeometry(QtCore.QRect(810, 490, 81, 31))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(CaritasPDRARiskDialog)
        QtCore.QMetaObject.connectSlotsByName(CaritasPDRARiskDialog)

    def retranslateUi(self, CaritasPDRARiskDialog):
        _translate = QtCore.QCoreApplication.translate
        CaritasPDRARiskDialog.setWindowTitle(_translate("CaritasPDRARiskDialog", "Caritas PDRA Risk Computation"))
        self.selectHHComboBox.setToolTip(_translate("CaritasPDRARiskDialog", "Select the household point layer with PDRA indicators"))
        self.selectHHComboBox.setWhatsThis(_translate("CaritasPDRARiskDialog", "Select the household point layer with PDRA indicators"))
        self.selectHHLabel.setText(_translate("CaritasPDRARiskDialog", "Select Household Layer with PDRA Indicators"))
        self.resultBasenameLabel.setText(_translate("CaritasPDRARiskDialog", "Basename for Resulting Layers"))
        self.resultBasenameLineEdit.setToolTip(_translate("CaritasPDRARiskDialog", "Resulting layers (in memory) will be named <basename_HAZ>, <basename_VUL>, <basename_CAP>, and <basename_RISK>."))
        self.resultBasenameLineEdit.setWhatsThis(_translate("CaritasPDRARiskDialog", "Resulting layers (in memory) will be named <basename_HAZ>, <basename_VUL>, <basename_CAP>, and <basename_RISK>."))
        self.selectIndicatorsLabel.setText(_translate("CaritasPDRARiskDialog", "Select Indicators/Fields to Compute Risk From"))
        self.hazLabel.setText(_translate("CaritasPDRARiskDialog", "Hazard"))
        self.hazListWidget.setToolTip(_translate("CaritasPDRARiskDialog", "Select the Hazard indicators to use for Risk computation"))
        self.hazListWidget.setSortingEnabled(True)
        self.vulListWidget.setToolTip(_translate("CaritasPDRARiskDialog", "Select the Vulnerabiliity indicators to use for Risk computation"))
        self.capListWidget.setToolTip(_translate("CaritasPDRARiskDialog", "Select the Capacity indicators to use for Risk computation"))
        self.vulLabel.setText(_translate("CaritasPDRARiskDialog", "Vulnerability"))
        self.capLabel.setText(_translate("CaritasPDRARiskDialog", "Capacity"))
        self.hazSelectAllBtn.setText(_translate("CaritasPDRARiskDialog", "Select All"))
        self.hazUnselectAllBtn.setText(_translate("CaritasPDRARiskDialog", "Unselect All"))
        self.vulUnselectAllBtn.setText(_translate("CaritasPDRARiskDialog", "Unselect All"))
        self.vulSelectAllBtn.setText(_translate("CaritasPDRARiskDialog", "Select All"))
        self.capUnselectAllBtn.setText(_translate("CaritasPDRARiskDialog", "Unselect All"))
        self.capSelectAllBtn.setText(_translate("CaritasPDRARiskDialog", "Select All"))
        self.label.setText(_translate("CaritasPDRARiskDialog", "<html><head/><body><p><span style=\" font-size:6pt;\">This plugin was made possible due to the efforts of NASSA/Caritas Philippines.</span></p></body></html>"))
        self.buttonBox.setToolTip(_translate("CaritasPDRARiskDialog", "Perform Risk Computation"))
